# Building our own GPT

A Dutch variation on the companion notebook to the [Zero To Hero](https://karpathy.ai/zero-to-hero.html) video on GPT.

In [1]:
# read it in to inspect it
with open('./ted_dutch_mono.nl', 'r', encoding='utf-8') as f:
    text = f.read()

In [2]:
print("length of dataset in characters: ", len(text))

length of dataset in characters:  16834509


In [3]:
# let's look at the first 1000 characters
print(text[:1000])

Voor mij begint dit verhaal ongeveer 15 jaar geleden,
toen ik een hospitaaldokter was aan de 'University of Chicago'.
Ik zorgde voor stervende mensen en hun families
in het zuiden van Chicago.
Ik observeerde wat er gebeurde met deze mensen en hun families
gedurende het verloop van hun terminale ziekte.
In mijn lab bestudeerde ik het weduwnaareffect,
een heel oud begrip in de sociale wetenschappen,
dat 150 jaar terug gaat
en bekend staat als 'sterven aan een gebroken hart'.
Wanneer ik sterf, verdubbelt het risico dat mijn vrouw sterft
in het eerste jaar.
Ik begon te zorgen voor een bepaalde patiënte,
een vrouw die leed aan dementie.
In dit geval werd ze,
in tegenstelling tot dit koppel,
verzorgd door haar dochter.
De dochter was uitgeput door het zorgen voor haar moeder.
De echtgenoot van de dochter
was ook ziek
door de uitputting van zijn vrouw.
Op een dag, toen ik naar huis reed,
kreeg ik een telefoontje van een vriend van de echtgenoot.
Hij belde me omdat hij gedeprimeerd was
door wa

In [4]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^`abcdefghijklmnopqrstuvwxyz~€‘’“”™£¨©°±²´º¼½¾ÁÉÏÒÓÖÜàáâãäåçèéêëìíîïñòóöùúûüāćėň˚ยรอ่​–—‘’“”…€™♪♫
163


In [10]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("Hoe gaat het?"))
print(decode(encode("Hoe gaat het?")))

[42, 80, 70, 2, 72, 66, 66, 85, 2, 73, 70, 85, 33]
Hoe gaat het?


In [6]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([16834509]) torch.int64
tensor([ 56,  80,  80,  83,   2,  78,  74,  75,   2,  67,  70,  72,  74,  79,
         85,   2,  69,  74,  85,   2,  87,  70,  83,  73,  66,  66,  77,   2,
         80,  79,  72,  70,  87,  70,  70,  83,   2,  19,  23,   2,  75,  66,
         66,  83,   2,  72,  70,  77,  70,  69,  70,  79,  14,   1,  85,  80,
         70,  79,   2,  74,  76,   2,  70,  70,  79,   2,  73,  80,  84,  81,
         74,  85,  66,  66,  77,  69,  80,  76,  85,  70,  83,   2,  88,  66,
         84,   2,  66,  66,  79,   2,  69,  70,   2,   9,  55,  79,  74,  87,
         70,  83,  84,  74,  85,  90,   2,  80,  71,   2,  37,  73,  74,  68,
         66,  72,  80,   9,  16,   1,  43,  76,   2,  91,  80,  83,  72,  69,
         70,   2,  87,  80,  80,  83,   2,  84,  85,  70,  83,  87,  70,  79,
         69,  70,   2,  78,  70,  79,  84,  70,  79,   2,  70,  79,   2,  73,
         86,  79,   2,  71,  66,  78,  74,  77,  74,  70,  84,   1,  74,  79,
          2,  73,  70,  85,  

In [8]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [11]:
block_size = 8
train_data[:block_size+1]

tensor([56, 80, 80, 83,  2, 78, 74, 75,  2])

In [12]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([56]) the target: 80
when input is tensor([56, 80]) the target: 80
when input is tensor([56, 80, 80]) the target: 83
when input is tensor([56, 80, 80, 83]) the target: 2
when input is tensor([56, 80, 80, 83,  2]) the target: 78
when input is tensor([56, 80, 80, 83,  2, 78]) the target: 74
when input is tensor([56, 80, 80, 83,  2, 78, 74]) the target: 75
when input is tensor([56, 80, 80, 83,  2, 78, 74, 75]) the target: 2


In [13]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[ 2, 87, 66, 79,  2, 70, 70, 79],
        [80, 83, 69, 70, 79, 16,  1, 42],
        [78,  2, 69, 70,  2, 88, 74, 79],
        [74, 68, 66, 85, 74, 70, 15, 80]])
targets:
torch.Size([4, 8])
tensor([[87, 66, 79,  2, 70, 70, 79,  2],
        [83, 69, 70, 79, 16,  1, 42, 74],
        [ 2, 69, 70,  2, 88, 74, 79, 84],
        [68, 66, 85, 74, 70, 15, 80, 78]])
----
when input is [2] the target: 87
when input is [2, 87] the target: 66
when input is [2, 87, 66] the target: 79
when input is [2, 87, 66, 79] the target: 2
when input is [2, 87, 66, 79, 2] the target: 70
when input is [2, 87, 66, 79, 2, 70] the target: 70
when input is [2, 87, 66, 79, 2, 70, 70] the target: 79
when input is [2, 87, 66, 79, 2, 70, 70, 79] the target: 2
when input is [80] the target: 83
when input is [80, 83] the target: 69
when input is [80, 83, 69] the target: 70
when input is [80, 83, 69, 70] the target: 79
when input is [80, 83, 69, 70, 79] the target: 16
when input is [80, 83,

In [14]:
print(xb) # our input to the transformer

tensor([[ 2, 87, 66, 79,  2, 70, 70, 79],
        [80, 83, 69, 70, 79, 16,  1, 42],
        [78,  2, 69, 70,  2, 88, 74, 79],
        [74, 68, 66, 85, 74, 70, 15, 80]])


In [16]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 163])
tensor(5.3625, grad_fn=<NllLossBackward0>)
	+€™>²£?ç♪dBéuò2lIė6AÜ9\$èá9î+āy;9p-`NTćย;d‘4A€ófxL$1♫2£567​—‘kÖê:uÖÏ\SsvCmïüytÒF	PöÖe9 L;<7=ch♫n5¨B


In [17]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [18]:
batch_size = 32
for steps in range(100): # increase number of steps for good results...

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.293283462524414


In [19]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	S9,ä5d´bÁél6…“<á=1@óL) â^ëÏX.äxJvj’ï4Aë’!Á—ÏUtcí['M€™♫…€F<7L>îuOYåX@ÏC\™♫naU*vÉîMNúòâ=Réû]ò;½£ëF]Dnéò£uåö—rC—i่v&©íWj””Ö™♫ร<íkL$KR´4 GäZP]“f;ùsãïwé,!rR
♪¨T˚ïo€=Ï’JRc-¾“Öà€x´?(sEóÖx	½™4*D​”	½A;û’5´êÓV%ç	é,!Mí#],‘O–ňå0Byň±xn‘ohOP==g>tcdMH=&ìย?ćâXX—=Bíอ˚í><~R:~Òºy2l˚7!ü&:J‘P92€3@moñ/y/ö-“V7=EY/eSÏ&²ºWtE5-¨ïėEw€'ãÜF±OYåėėย©+
“ãhMòò`Wüîj±)c่#♫`X>♪PS©W8Vtkjîñ&ÒäÉ3Tåอûè…päñ,1ñ²ยîP2 ÁSú>s/sìm#)½—Rx	=c9.8z$LėPåoNSQàR6j±¨ย°.7X​dèň“TOgH£“úêÒÁć¼"Ö.sykÒyèîsr6Gc#]ö½m¾O*Hj$y;b.U¨‘ûāNk0±òIoº)yā£™♫2‘M;+a˚jÜ)


In [20]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3))
a = a / torch.sum(a, 1, keepdim=True)
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [21]:
# consider the following toy example:

torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [22]:
# We want x[b,t] = mean_{i<=t} x[b,i]
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [23]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [24]:
# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

True

In [25]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [26]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

Notes:

- Attention is a communication mechanism. Can be seen as nodes in a directed graph looking at each other and aggregating information with a weighted sum from all nodes that point to them, with data-dependent weights.
- There is no notion of space. Attention simply acts over a set of vectors. This is why we need to positionally encode tokens.
- Each example across batch dimension is of course processed completely independently and never "talk" to each other 
- In an "encoder" attention block just delete the single line that does masking with tril, allowing all tokens to communicate. This block here is called a "decoder" attention block because it has triangular masking, and is usually used in autoregressive settings, like language modeling.
- "self-attention" just means that the keys and values are produced from the same source as queries. In "cross-attention", the queries still get produced from x, but the keys and values come from some other, external source (e.g. an encoder module)
- "Scaled" attention additional divides wei by 1/sqrt(head_size). This makes it so when input Q,K are unit variance, wei will be unit variance too and Softmax will stay diffuse and not saturate too much. Illustration below

In [27]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [28]:
k.var()

tensor(1.0449)

In [29]:
q.var()

tensor(1.0700)

In [30]:
wei.var()

tensor(1.0918)

In [31]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [32]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [33]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [34]:
x[:,0].mean(), x[:,0].std() # mean,std of one feature across all batch inputs

(tensor(0.1469), tensor(0.8803))

In [35]:
x[0,:].mean(), x[0,:].std() # mean,std of a single input from the batch, of its features

(tensor(-9.5367e-09), tensor(1.0000))

In [37]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

# wget https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt
with open('ted_dutch_mono.nl', 'r', encoding='utf-8') as f:
    text = f.read()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


0.222371 M parameters
step 0: train loss 5.2415, val loss 5.2443
step 100: train loss 2.5942, val loss 2.5906
step 200: train loss 2.4523, val loss 2.4567
step 300: train loss 2.3835, val loss 2.3827
step 400: train loss 2.3231, val loss 2.3103
step 500: train loss 2.2455, val loss 2.2337
step 600: train loss 2.1922, val loss 2.1790
step 700: train loss 2.1500, val loss 2.1517
step 800: train loss 2.1154, val loss 2.1071
step 900: train loss 2.0760, val loss 2.0654
step 1000: train loss 2.0545, val loss 2.0461
step 1100: train loss 2.0120, val loss 2.0184
step 1200: train loss 2.0129, val loss 2.0024
step 1300: train loss 1.9820, val loss 1.9652
step 1400: train loss 1.9832, val loss 1.9686
step 1500: train loss 1.9558, val loss 1.9355
step 1600: train loss 1.9403, val loss 1.9237
step 1700: train loss 1.9129, val loss 1.9123
step 1800: train loss 1.9187, val loss 1.9082
step 1900: train loss 1.9043, val loss 1.8973
step 2000: train loss 1.8731, val loss 1.8848
step 2100: train loss 1.